Q := Rationals();
R<k> := PolynomialRing(Integers());

p := 2*k^2 - 1;
q := 2*k^2 + 2*k + 1;
r := 2*k + 1;

A := 8*k^6 + 8*k^5 - 2*k^3 - k^2;
B := 4*k^7*(k+1)*p*q;

// Check the corrected discriminant identity for X^2 + A X + B.
assert A^2 - 4*B eq k^4*r^2;

/*
The roots are
    e1 = 0,
    e2 = -k^2*p*q,
    e3 = -4*k^5*(k+1).

Gusic--Tadic requires checking squarefree divisors of:
    (e1-e2)(e1-e3),  (e2-e1)(e2-e3),  (e3-e1)(e3-e2).

The following are squarefree generator lists for these three products.
The constant 2 is included where the content contributes the squareclass 2.
*/
FactorLists := [
    [R!2, k, k+1, p, q],     // from  4*k^7*(k+1)*p*q
    [k, p, q, r],            // from -k^4*p*q*r
    [R!2, k, k+1, r]         // from  4*k^7*(k+1)*r
];

// All subset-products of a list S.  These are the squarefree divisors
// generated by S, up to sign.
function SubsetProducts(S)
    products := [R!1];

    for f in S do
        old_products := products;
        products cat:= [h*f : h in old_products];
    end for;

    return products;
end function;

// Returns true iff k0 satisfies the Gusic--Tadic condition.
// If it fails, the second return value is h with h(k0) square.
function GTCondition(k0)
    for S in FactorLists do
        for h in SubsetProducts(S) do
            if Degree(h) gt 0 then
                // Check both h and -h, since divisors are defined up to units.
                for eps in [1, -1] do
                    hh := eps*h;
                    if IsSquare(Q!Evaluate(hh,k0)) then
                        return false, hh;
                    end if;
                end for;
            end if;
        end for;
    end for;

    return true, R!1;
end function;

// Specialized curve at k = k0:
//     Y^2 = X^3 + A(k0) X^2 + B(k0) X.
function SpecializedCurve(k0)
    return EllipticCurve([
        Q!0, Q!Evaluate(A,k0), Q!0, Q!Evaluate(B,k0), Q!0
    ]);
end function;

// Check the chosen specialization k = 14.
k0 := 14;
ok, problematic_factor_if_not_1 := GTCondition(k0);
print "GT condition at k = 14:", ok;
assert ok;

// Compute the rank of the specialized curve.
E14 := SpecializedCurve(k0);
lower, upper := RankBounds(E14);

print "E_14 =", E14;
print "Rank bounds for E_14:", lower, upper;
assert lower eq 0 and upper eq 0;